#Arianna Wills

Arianna is a professional ballet and jazz dancer. She qualified as a
teacher at the Royal Academy of Dance (RAD), and completed her
student’s exams at the Imperial Society of Teachers of Dance
(ISTD). She is an experienced teacher, having worked for over 15 years in Italy
and UK with children and adults of all ages and levels.

Arianna is also a Pilates and fitness trainer, seniors’ instructor,
diet and supplementation consultant, a rehab advisor and a Sports and
Remedial Massage therapist, having graduated at the North London School
of Sports Massage.

     



