#Classes

Eos Dance School follows the method of the [Royal Academy of Dance](http://www.rad.org.uk/)
for the preparation of exams. Qualifications achieved with the RAD
are recognised by the Ofqual and valid on the Qualifications and
Credit Framework. Please see our link page for further details
about the RAD and QCDA.

Free classes are also available to offer children the chance of
expressing their personality through dance and movement. We firmly
believe enjoyment to be a pre-requisite to move to any further
stage. Children showing talent, desire and dedication to dance will
be subsequently encouraged and guided to pursue a professional
career.

Children are welcome to enrol at any time of the year. For health
and safety reasons, formal
registration is a requirement to dance in our classes. Please refer to our enrolment section to
download the necessary documents and full information about your
preferred location.

Children’s parties
We are twinned to www.tinlidsparties.com. Tin Lids Parties offer themed parties for children and adults. Their parties include dancing, performing, craft, high-energy activities with games, creative workshops and performance opportunities. Our themes include Glee, High School Musical, Going Gaga, Disco Divas, Mamma Mia, Beautiful Ballerinas, Hip Hop and more... Tin Lids Parties are available to meet your individual requests.  
