#Contact

Arianna Wills

Email: <info@eosdance.co.uk>

Phone: 07833 148510




VENUES
----------
$schools:schoolFullAddress()$


<!--
**[Goodrich Community Primary School](http://www.goodrich.org.uk/)**

Dunstans Road  
East Dulwich  
London SE22 0EP  
Tel: 020 8693 1050  
Fax:020 8299 2775  
Email: <office@goodrich.southwark.sch.uk>



**[Christ Church Street French Nursery Ltd](http://www.findmyschool.co.uk/schooldetails.aspx?id=99804)**

3 Caversham Street  
London SW3 4AF  
Tel: 020 7351 9648

12 Alpha Place  
London SW3 5SZ  
Tel: 020 7351 9648



** [St. Margaret’s School](http://www.st-margarets.co.uk) **

18 Kidderpore Gardens
Hampstead
London NW3 7SR

Tel: 020 7435 2439 - 020 7431 1308
Email: <enquiry@st-margarets.co.uk>



** [St. Paul’s Steiner School](http://stpaulssteinerschool.org) **

1 St Paul's Road
London N1 2QH UK

Tel: 020 7226 4454
Fax: 020 72262062

E-mail: <office@stpaulssteinerschool.org>

-->

