#Contact

Arianna Wills

Email: <info@eosdance.co.uk>

Phone: 07833 148510




VENUES
----------
$schools:schoolFullAddress()$


VENUES

Goodrich Community Primary School

Dunstans Road
East Dulwich
London SE22 0EP
Tel: 020 8693 1050
Fax:020 8299 2775
Email:office@goodrich.southwark.sch.uk

Goodliffe Hall

Christ Church Gipsy Hill, 
1 Highland Road, 
London 
SE19 1DP
Tel: 020 8761 5927 
Email: goodliffehall@gipsyhill.org.uk

Antenna Studios
Bowyers Yard, Haynes Lane
London
SE19 3AN
Tel: 020 8653 5200
Email: info@antennastudios.co.uk







-->

