#Enrolment

To enrol, please download and fill in the registration form. Applicable fees are listed in the “Fee list” of
each location.

Each school has also its specific guidelines, calendar, and initiatives. We recommend reading the
full documentation prior registration. Do feel free to contact us if you have any query or need further
details.

Private coaching can be arranged to suit individual needs and goals. We are happy to answer any
enquiries regarding specific goals or request of advice.


<div class="pdfLinks">

[EOS Dance School Registration Form](EOS Dance School - Registration form.pdf)

[Calendar 2011-2012](pdfs/Class Calendar 2011-2012.pdf)

$schools:schoolPdfs()$
  
</div>


