# Welcome to the Eos School of Dance

We are a new dance school serving south and central London teaching
classes in ballet, hip-hop and streetdance. We offer after-school
clubs for children, adult classes, and private coaching. Bilingual
French and English classes are also available.

Our classes currently run at the following locations:

$schools:schoolShort()$


•	Goodrich School (Dulwich)
•	Goodliffe Hall, Christ Church (Gipsy Hill)
•	Antenna Studios (Crystal Palace)
•	Central London (private coaching)
