<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
   <title>$sitetitle$ - $pagetitle$</title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <link rel="stylesheet" type="text/css" href="css/screen.css" />
   <link rel="stylesheet" type="text/css" media="print" href="css/print.css" />
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js" type="text/javascript"></script>
   <script src="js/nav.js" type="text/javascript"></script>
</head>
<body >
<div id="doc" class="yui-t2">
  <div id="logoimg">
<!--
   <div id="hd" role="banner">
     <h1>Eos Dance School</h1>
   </div>
-->
   <div id="bd" role="main">
	<div id="yui-main">

	<div class="yui-b">
	<div class="yui-g">
	  $contents$
	</div>
	</div>
	</div>
	<div class="yui-b">$nav$</div>
	</div>
   <div id="ft" role="contentinfo">
     <span>
   <br/>
   <br/>
   <br/>
   <br/>
   	&nbsp;
   	Email: <script type="text/javascript"
    >
<!--
h='&#x65;&#x6f;&#x73;&#100;&#x61;&#110;&#x63;&#x65;&#46;&#x63;&#x6f;&#46;&#x75;&#x6b;';a='&#64;';n='&#x61;&#114;&#x69;';e=n+a+h;
document.write('<a h'+'ref'+'="ma'+'ilto'+':'+e+'">'+'<code>'+e+'</code>'+'<\/'+'a'+'>');
// -->
</script
    ><noscript
    >&#x61;&#114;&#x69;&#32;&#x61;&#116;&#32;&#x65;&#x6f;&#x73;&#100;&#x61;&#110;&#x63;&#x65;&#32;&#100;&#x6f;&#116;&#32;&#x63;&#x6f;&#32;&#100;&#x6f;&#116;&#32;&#x75;&#x6b;</noscript
    >

|  Phone: 07833 148510
<!--
     <img id="logo" src="generated_images/grand_jete_with_sun_background_and_gradient.png"/>
-->
	</span>
   </div>
  </div>
</div>
</body>
</html>
