#Timetable

* * * * *
##MONDAY 

###Goodrich School - Ballet

3:30 to 4:00pm – Nursery

4:00 to 4:40pm – Reception + Year 1

4:40 to 5:20pm – Year 2 upwards 

* * * * *
##TUESDAY

###Antenna Studios – Street dance

4 to 4:30pm – Kids  (4 to 7 years old)

4:30 to 5:10pm – Junior (8 to 12 years old)

5:10 to 5:50 – Biggies (13+)

* * * * *

##WEDNESDAY 

###Antenna Studios – Pilates and Dance

Timetable TBC

* * * * *
##THURSDAY

###Goodliffe Hall, Christ Church – Ballet

4 to 4:30pm – Pre-Primary (4 and 5 years old)

4:30 to 5:10pm – Primary and Grade 1 (6 and 7 years old)

5:10 to 5:50 – Grade 2 and 3 (8 to 10 years old)

5:50 to 6:30 – Seniors (11+)

* * * * *
##FRIDAY 

###Goodrich School – Street dance

3:50 to 4:30pm – Reception to Year 2

4:30 to 5:10pm – Year 3 to Year 6


<!--
![](generated_images/img_250/800px-Grandjete.jpg)
-->
