#Timetable

MONDAY (Goodrich School - Ballet)

3:30 to 4:00pm – Nursery

4:00 to 4:40pm – Reception

4:40 to 5:20pm – Year 1 upwards



TUESDAY



WEDNESDAY (Goodliffe Hall, Christ Church – Street dance)

3:45 to 4:25pm – Kids (5 and 6 years old)

4:25 to 5:05pm – Junior (7 to 9 years old)

5:05 to 5:45 – Biggies (10 to 13 years old)

5:45 to 6:30 – Seniors (14+)


THURSDAY (Goodliffe Hall, Christ Church – Ballet)

3:45 to 4:25pm – Pre-Primary (4 and 5 years old)

4:25 to 5:05pm – Primary and Grade 1 (6 and 7 years old)

5:05 to 5:45 – Grade 2 and 3 (8 to 10 years old)

5:45 to 6:30 – Seniors (11+)


FRIDAY (Goodrich School – Street dance)

3:50 to 4:30pm – Reception to Year 2

4:30 to 5:10pm – Year 3 to Year 6


<!--
![](generated_images/img_250/800px-Grandjete.jpg)
-->